name: Go Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    setps:
      - name: checkout code
        users: actions/checkout@v3

      - name: setup go lang
        users: actions/setup-go@v4
        with:
          go-version: "1.23.4"

      - name: install dependencies
        run: go mod tidy
        working-directory: ./go-app

      - name: test
        run: go test ./... -v
        working-directory: ./go-app

      - name: build
        run: go build -v .
        working-directory: ./go-app
